### ISSUE TITLE
Upload 200 mb files

### ISSUE THREAD

**Issue by xardover** [remisa-yousefvand/virto-bot#3]
Can you implement [this feature](https://developers.virustotal.com/v2.0/reference#file-scan-upload-url) of Virustotal API?

It can upload files up to 200 mb but they need to be uploaded on third-party site, maybe some kind of temporarily storage on server

**Comment by xardover** [comment]
also: bot does not process ~25-30 mb files, the limit is 32 but these files not being processed too

**Comment by xardover** [comment]
```
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: file is too big
    at request.then.resp (/usr/src/virto-bot/node_modules/node-telegram-bot-api/src/telegram.js:280:15)
    at tryCatcher (/usr/src/virto-bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/virto-bot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/virto-bot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/src/virto-bot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/src/virto-bot/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/src/virto-bot/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/src/virto-bot/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/src/virto-bot/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/virto-bot/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
```

after uploading 20 mb file

**Comment by remisa-yousefvand** [comment]
This is not a `Virustotal` error yet. It is the `Telegram` error since the file is too big according to telegram limitations. So even if you acquire the permission from `Virustotal` for uploading big files via special upload URL, you cannot use `Telegram` as the interface unless you acquire the same permission from `Telegram` too.

**Comment by remisa-yousefvand** [comment]
Telegram upload limitation
